export const TYPES = {
 ADD_TO_CART: 'ADD_TO_CART',
 REMOVE_ONE_FROM_CART: 'REMOVE_ONE_FROM_CART',
 REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
 CLEAR_CART: 'CLEAR_CART',
 GET_TOTAL: 'GET_TOTAL',
 GET_PRODUCTS: 'GET_PRODUCTS',
};
