export * from './About';
export * from './Answers';
export * from './Contact';
export * from './Privacy';
export * from './Register';
export * from './Work';
export * from './Cart';
export * from './Profile';
export * from './Checkout';
//export * from './UserEdit'
